version: "2"

run:
  go: "1.23"
  tests: true
  build-tags:
    - bench
    - !bench

linters:
  settings:
    funlen:
      lines: 150
      statements: 80
  exclusions:
    rules:
      - path: '(.+)\.go$'
        text: should have a package comment
      - path: _test\.go
        linters:
          - errcheck
          - dupl
          - gocyclo
          - gosec
      - path: "../../../go/pkg/mod"
        linters:
          - typecheck
    paths:
      - bin
      - vendor
      - var
      - tmp
      - .cache
  default: none
  enable:
    - asciicheck
    - dogsled
    - dupl
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
